name: Automerge

on:
  push:
    branches:
      - 'release/release_*'

jobs:
  merge_forward:
    name: Merges release branches back to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge
        run: |
          git config user.name 'Automerge'
          git config user.email 'msteves@paychex.com'
          
          source_branch = ${GITHUB_REF}
          
          for i in `git branch | grep release/release_* | sort`
          do
            if [ `echo $i | cut -d _ -f 2` -le `echo ${GITHUB_REF} | cut -d _ -f 2`]
            then
              continue
            fi
            
            git checkout $i
            git merge --no-ff source_branch
            git push
            
            source_branch = $i
            
          done
          
          git checkout develop
          git merge --no-ff source_branch
          git push