name: Automerge

on:
  push:
    branches:
      - 'release/release_*'

jobs:
  merge_forward:
    name: Merges release branches back to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge
        shell: bash {0}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'Automerge'
          git config user.email 'msteves@paychex.com'
          
          source_branch=${GITHUB_REF}
          echo "Initial source branch - $source_branch"
          
          # Get remote branches
          branches=(`git branch -r`)
          # Strip off origin/ from the branch names, limit to release branches, and sort
          release_branches=$(printf -- '%s\n' "${branches[@]}" | cut -c 8- | grep release/release_* | sort | tr '\n' ' ')
          release_branches+=("develop")
          
          for release_branch in ${release_branches[@]}
          do
            echo "Processing branch $release_branch"
            # Parse both branches down to the date component and compare
            if [ $release_branch != 'develop' ] && [ `echo $release_branch | cut -d _ -f 2` -le `echo ${GITHUB_REF} | cut -d _ -f 2` ]
            then
              echo "Release branch $release_branch is less than or equal to source release branch $source_branch - SKIPPING"
              continue
            fi
            
            echo "Creating pull request for auto merge"
            pull_request_url=`gh pr create --head $source_branch --base $release_branch --title "Automatic merge" --body "Automatic merge from $source_branch to $release_branch" | tail -1`
            if [ $? -ne 0 ]
              echo "PR creation failed, PR already exists - $pull_request_url"
              exit 0
            fi
            
            echo "Auto merging PR $pull_request_url"
            gh pr merge $pull_request_url --admin
            if [ $? -ne 0 ]
            then
              echo "Merge failed. Updating pull request."
              gh pr edit $pull_request_url --title "Automatic merge failure" --body "There was a merge conflict automatically merging this branch" --add-reviewer paychex-msteves
              exit 0
            fi
            
            source_branch=$release_branch
            echo "Source branch set to $release_branch"
            
          done