name: Automerge

on:
  push:
    branches:
      - 'release/release_*'

jobs:
  merge_forward:
    name: Merges release branches back to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge
        run: |
          git config user.name 'Automerge'
          git config user.email 'msteves@paychex.com'
          
          source_branch=${GITHUB_REF}
          echo "Initial source branch - $source_branch"
          
          for i in `git branch | grep release/release_* | sort`
          do
            echo "Processing release branch $i"
            if [ `echo $i | cut -d _ -f 2` -le `echo ${GITHUB_REF} | cut -d _ -f 2`]
            then
              echo "Release branch $i is less than or equal to source release branch $source_branch - SKIPPING"
              continue
            fi
            
            echo "Checking out release branch $i"
            git checkout $i
            echo "Merging source branch $source_branch into branch $i"
            git merge --no-ff source_branch
            echo "Pushing commit"
            git push
            
            source_branch=$i
            echo "Source branch set to $i"
            
          done
          
          echo "Checking out develop"
          git checkout develop
          echo "Merging source branch $source_branch into branch develop"
          git merge --no-ff source_branch
          echo "Pushing commit"
          git push